[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { workspace = true, features = ["fancy"] }
thiserror = { workspace = true }

[dev-dependencies]
test-case = "3.3.1"
