[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Ctarget-cpu=skylake"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-cpu=skylake"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=skylake"]
