[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static target-cpu=haswell"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=haswell"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=haswell"]